#!/usr/bin/env python3
"""
Generate the launcher's pixel-art icons: one per system, Favorites and
Recently Played, and the header ship. (Settings keeps its gear glyph.)

    python gen-icons.py <launcher/icons.h> [preview.png]

All art here is original, drawn for this project as 16x16 pixel sprites: a
console's silhouette in its colours, not any company's logo or artwork, so the
icons carry no licence question. The launcher scales them by whole pixels
(nearest neighbour), which keeps the edges crisp at any resolution.

Writes the C header the launcher includes (committed, so a build does not need
Python). The preview PNG needs Pillow (Windows' python has it; WSL's does not).

Each icon: a palette (one character per colour, '.' is transparent) and 16 rows
of 16 characters. Keys are the launcher's system dir_name, or one of the
special names below.
"""
import sys

ICONS = {}


def icon(name, palette, art):
    rows = [r for r in art.strip('\n').split('\n')]
    assert len(rows) == 16, f'{name}: {len(rows)} rows'
    for i, r in enumerate(rows):
        assert len(r) == 16, f'{name} row {i}: {len(r)} columns: {r!r}'
        for c in r:
            assert c == '.' or c in palette, f'{name} row {i}: colour {c!r} not in palette'
    ICONS[name] = (palette, rows)


# --------------------------------------------------------------- Nintendo ---
icon('nes', {'W': 'e4e4e4', 'L': 'b8b8b8', 'K': '1e1e1e', 'D': '565656', 'R': 'd03030', 'S': '8a8a8a'}, '''
................
................
................
.LLLLLLLLLLLLLL.
LWWWWWWWWWWWWWWL
LLLLLLLLLLLLLLLL
LKKKKKKKKKKKKKKL
LKKSSSSSSSSSSKKL
LKKSSSSSSSSSSKKL
LKKKKKKKKKKKKKKL
DDDDDDDDDDDDDDDD
DRDDKKKDKKKDDDDD
DDDDKKKDKKKDDDDD
.DDDDDDDDDDDDDD.
................
................
''')

icon('snes', {'W': 'e6e6ee', 'L': 'c4c4d0', 'S': '8c8c9c', 'K': '3a3a46', 'P': '6a4ca8', 'V': 'a898d8'}, '''
................
................
................
....SSSSSSSS....
...SKKKKKKKKS...
..LLKKKKKKKKLL..
.WWWWWWWWWWWWWW.
LLLLLLLLLLLLLLLL
LPPLLLLLLLLVVVLL
LPPLLLLLLLLVPVLL
LLLLLLLLLLLVVVLL
LLLLLLLLLLLLLLLL
.SSSSSSSSSSSSSS.
................
................
................
''')

icon('gb', {'G': 'c8c4bc', 'H': 'e0ddd6', 'D': '6c6c7c', 'L': '9bbc0f', 'l': '306230', 'K': '2a2a2a', 'M': '8c1c4c', 'S': '8e8a82'}, '''
...HHHHHHHHHH...
...GDDDDDDDDG...
...GDLLLLLLDG...
...GDLlLLlLDG...
...GDLLLLLLDG...
...GDLlllLLDG...
...GDLLLLLLDG...
...GDDDDDDDDG...
...GGGGGGGGGG...
...GGKGGGGGGG...
...GKKKGGGGMG...
...GGKGGGGMGG...
...GGGGGGGGGG...
...GGGGGGGGGG...
...GGGGGSGSGG...
....GGGGGGGGG...
''')

icon('gbc', {'P': '7a3cb0', 'H': '9c64d2', 'D': '2c2c3a', 'L': '64b4f0', 'l': 'f0c040', 'K': '1e1e28', 'B': 'e8e8f0', 'S': '4c2470'}, '''
...HHHHHHHHHH...
...PDDDDDDDDP...
...PDLLLLLLDP...
...PDLllLLLDP...
...PDLllLLLDP...
...PDLLLLLLDP...
...PDLLLLLLDP...
...PDDDDDDDDP...
...PPPPPPPPPP...
...PPKPPPPPPP...
...PKKKPPPPBP...
...PPKPPPPBPP...
...PPPPPPPPPP...
...PPPPPPPPPP...
...PPPPPSPSPP...
....PPPPPPPPP...
''')

icon('gba', {'B': '4a3ca0', 'H': '6c5cc8', 'D': '24243a', 'S': '78c0f0', 's': 'f0f0ff', 'K': '18182a', 'Y': 'e8e8f0'}, '''
................
................
................
................
..HHHHHHHHHHHH..
.BBBDDDDDDDDBBB.
BBBBDSSSSSSDBBBB
BKBBDSsSSSSDBYBB
KKKBDSSSSSSDBBYB
BKBBDSSSSSSDBYBB
BBBBDDDDDDDDBBBB
.BBBBBBBBBBBBBB.
..BB........BB..
................
................
................
''')

icon('n64', {'G': '9a9aa4', 'H': 'c0c0c8', 'D': '5a5a66', 'K': '22222a', 'Y': 'f0c818', 'B': '2c64d8', 'g': '1e9c48', 'R': 'd83030'}, '''
................
................
................
..HHHHHHHHHHHH..
.GGGGGGGGGGGGGG.
GGKGGGGRGGYGYGGG
GKKKGGGGGGGYGYGG
GGKGGGGGGGgGBGGG
GGGGGGGGGGGGGGGG
GGGGGDDDDDDGGGGG
.GGGGGDDDDGGGGG.
.GGGG.GDDG.GGGG.
..GG..GKKG..GG..
......GDDG......
.......GG.......
................
''')

# ------------------------------------------------------------------- Sega ---
icon('genesis', {'K': '1c1c1c', 'G': '505050', 'H': '7a7a7a', 'R': 'd02020', 'W': 'dcdcdc'}, '''
................
................
................
................
...HHHHHHHHHH...
..KKKGGGGGGKKK..
.KKKKGKKKKGKKKK.
KKKKKGGGGGGKKKKK
KKKKKKKKKKKKKKKK
KRKKKKKKKKKKWWKK
KKKKKKKKKKKKKKKK
.KKKKKKKKKKKKKK.
................
................
................
................
''')

icon('mastersystem', {'K': '1c1c1c', 'G': '4a4a4a', 'H': '6e6e6e', 'R': 'd82828', 'W': 'e0e0e0'}, '''
................
................
................
................
.HHHHHHHHHHHHHH.
KKKKKKKKKKKKKKKK
KGGGGGGGGGGGGGGK
KRRRRRRRRRRRRRRK
KKKKKKKKKKKKKKKK
KKKWWKKKKKKKKRKK
KKKKKKKKKKKKKKKK
.KKKKKKKKKKKKKK.
................
................
................
................
''')

icon('gamegear', {'K': '1e1e22', 'H': '3c3c44', 'D': '0c0c10', 'S': '4a88d8', 's': 'a8d8ff', 'B': '2c50c8', 'R': 'd83030'}, '''
................
................
................
................
..HHHHHHHHHHHH..
.KKKDDDDDDDDKKK.
KKKKDSSSSSSDKKKK
KHKKDSsSSSSDKRKK
HHHKDSSSSSSDKKBK
KHKKDSSSSSSDKRKK
KKKKDDDDDDDDKKKK
.KKKKKKKKKKKKKK.
..KK........KK..
................
................
................
''')

icon('dreamcast', {'W': 'f2f2f2', 'L': 'c8c8cc', 'S': '9c9ca4', 'O': 'f07818', 'K': '3a3a40'}, '''
................
................
................
..WWWWWWWWWWWW..
.WWWWWWWWWWWWWW.
WWWWWOOOOOWWWWWW
WWWWOWWWWWOWWWWW
WWWOWWOOOWWOWWWW
WWWOWOWWWOWOWWWW
WWWOWOWWOOWOWWWW
WWWWOWOWWWOWWWWW
WWWWWOWOOOWWWWWW
LLLLLLLLLLLLLLLL
LKLKLLLLLLLLLLLL
.SSSSSSSSSSSSSS.
................
''')

# ------------------------------------------------------------------ Atari ---
icon('atari2600', {'K': '1e1a16', 'G': '3c3630', 'W': '8c5a2c', 'w': 'a8723c', 'S': 'c8c8c8', 'O': 'e08c28'}, '''
................
................
................
................
.KKKKKKKKKKKKKK.
KKGGGGGGGGGGGGKK
KKGKKKKKKKKKKGKK
KSKSKSKKKKSKSKSK
KKKKKKKKKKKKKKKK
WWwWWwWWWwWWwWWW
WwWWWWwWWWWwWWWW
WWWwWWWWwWWWWwWW
.WWWWWWWWWWWWWW.
................
................
................
''')

icon('atari7800', {'K': '1c1c1c', 'G': '3e3e42', 'S': 'b4b4bc', 'H': 'dcdce4', 'R': 'd02828'}, '''
................
................
................
................
....GGGGGGGG....
...GGKKKKKKGG...
..GGKKKKKKKKGG..
.KKKKKKKKKKKKKK.
KSSSSSSSSSSSSSSK
KHHHHHHHHHHHHHHK
KKKKKKKKKKKKKRKK
KKKKKKKKKKKKKKKK
.KKKKKKKKKKKKKK.
................
................
................
''')

icon('atari800', {'B': 'd8c8a4', 'H': 'ece0c4', 'D': 'a89874', 'K': '3a3228', 'k': '5c5244', 'O': 'e07c20'}, '''
................
................
................
................
..HHHHHHHHHHHH..
.BBBBBBBBBBBBBB.
BBBBBBBBBBBBBOBB
BKkKkKkKkKkKkKBB
BkKkKkKkKkKkKkBB
BBKkKkKkKkKkKkKB
BBkKKKKKKKKKkBBB
DDDDDDDDDDDDDDDD
.DDDDDDDDDDDDDD.
................
................
................
''')

# ------------------------------------------------------------------- NEC ----
icon('pce', {'W': 'f4f4f4', 'L': 'cccccc', 'S': '8a8a8a', 'K': '2a2a2a', 'O': 'f08020', 'B': '2c64c8'}, '''
................
................
................
................
...WWWWWWWWWW...
..WWWWWWWWWWWW..
..WLLLLLLLLLLW..
..WKKKKKKKKKKW..
..WLLLLLLLLLLW..
..WWWWWWWWWOBW..
..WWWWWWWWWWWW..
..LLLLLLLLLLLL..
...SSSSSSSSSS...
................
................
................
''')

icon('pcesupergrafx', {'K': '1e1e1e', 'G': '3a3a3a', 'H': '5c5c5c', 'S': 'a0a0a8', 'R': 'd83030', 'Y': 'e8c020'}, '''
................
................
................
.HHHHHHHHHHHHHH.
KKKKKKKKKKKKKKKK
KGGGGGGGGGGGGGGK
KGKKKKKKKKKKKKGK
KGGGGGGGGGGGGGGK
KKKKKKKKKKKKKKKK
KSSSSSSSSSSSSSSK
KKKKKKKKKKKKYRKK
KKKKKKKKKKKKKKKK
.KKKKKKKKKKKKKK.
................
................
................
''')

# --------------------------------------------------------------- Sinclair ---
icon('zxspectrum', {'K': '1a1a1a', 'G': '3a3a3a', 'k': '5a5a5a', 'R': 'e02828', 'Y': 'f0d020', 'g': '20b040', 'C': '28a8e8'}, '''
................
................
................
................
................
.KKKKKKKKKKKKKK.
KKKKKKKKKKKRYgCK
KkGkGkGkGkRYgCKK
KGkGkGkGkRYgCkGK
KkGkGkGkRYgCGkGK
KGkGkGkRYgCkGkGK
KKKKKKKKKKKKKKKK
.KKKKKKKKKKKKKK.
................
................
................
''')

# ------------------------------------------------------------------- Sony ---
icon('psx', {'G': 'b4b4bc', 'H': 'd2d2da', 'S': '8a8a94', 'K': '3c3c46', 'R': 'e03838', 'Y': 'e8c020', 'g': '20a050', 'B': '3070d8'}, '''
................
................
................
.HHHHHHHHHHHHHH.
GGGGGGGGGGGGGGGG
GGGGSSSSSSGGGGGG
GGGSGGGGGGSGGGGG
GGSGGGGGGGGSGRGG
GGSGGGKKGGGSGYGG
GGSGGGKKGGGSGgGG
GGGSGGGGGGSGGBGG
GGGGSSSSSSGGGGGG
GGGGGGGGGGGGGGGG
.SSSSSSSSSSSSSS.
................
................
''')

icon('psp', {'K': '161618', 'H': '3a3a40', 'D': '060608', 'S': '3a70c8', 's': '9cc8f8', 'L': '8c8c94'}, '''
................
................
................
................
.HHHHHHHHHHHHHH.
KKKDDDDDDDDDDKKK
KLKDSSSSSSSSDKLK
LLLDSSssSSSSDLKL
KLKDSSsSSSSSDKLK
KKKDSSSSSSSSDKKK
KKKDDDDDDDDDDKKK
.KKKKKKKKKKKKKK.
................
................
................
................
''')

# ----------------------------------------------------------------- Arcade ---
def cabinet(name, body, marquee, marquee_hi, screen):
    icon(name, {'C': body, 'c': marquee_hi, 'M': marquee, 'K': '141418', 'S': screen,
                's': 'f0f0f0', 'R': 'e02828', 'Y': 'f0d020', 'D': '2a2a30'}, '''
...CCCCCCCCCC...
...CMMMMMMMMC...
...CMccMMccMC...
...CCCCCCCCCC...
...CKKKKKKKKC...
...CKSSSSSsKC...
...CKSSSSsSKC...
...CKSSSSSSKC...
...CKSSSSSSKC...
...CKKKKKKKKC...
..CCCCCCCCCCCC..
..CDDKDDRDYDDC..
...CCCCCCCCCC...
...CCCCCCCCCC...
...CCCCCCCCCC...
...CDDDDDDDDC...
''')


cabinet('arcade', '2c48a8', 'f0c020', 'fff4b0', '30b8a0')     # blue body, yellow marquee
cabinet('mame', '2a2a2e', 'e04030', 'ffb0a0', '4c8cf0')       # black body, red marquee
cabinet('neogeo', 'c02828', '1a1a1a', 'f0c020', '60c8f0')     # red cabinet, black/gold marquee
cabinet('cps1', '3060d0', 'f04040', 'ffd0d0', 'f0d040')       # three CPS generations, three colours
cabinet('cps2', '208c48', 'f0d040', 'ffffff', '40a0f0')
cabinet('cps3', '7a34b8', '40d0f0', 'e0ffff', 'f07030')

# -------------------------------------------------------------------- Doom ---
icon('doom', {'R': 'b02018', 'r': 'd84028', 'K': '1a0a08', 'Y': 'f8d040', 'W': 'f0e8d8', 'B': '6a1410'}, '''
................
..B..........B..
..RB........BR..
..RRB.BBBB.BRR..
...RRRRRRRRRR...
..RRRRRRRRRRRR..
..RrKKRRRRKKrR..
..RKYYKRRKYYKR..
..RrKKRRRRKKrR..
..RRRRRKKRRRRR..
...RRRRRRRRRR...
...RKWKWKWKWR...
...RWKWKWKWKR...
....RRRRRRRR....
.....BBBBBB.....
................
''')

# ---------------------------------------------------------- special items ---
icon('favorites', {'Y': 'f8c820', 'H': 'fff0a0', 'O': 'd89010'}, '''
................
.......HY.......
.......HY.......
......HYYO......
......HYYO......
.HHHHHYYYYYYYYO.
..HYYYYYYYYYYO..
...HYYYYYYYYO...
....HYYYYYYO....
....HYYYYYYO....
...HYYYYYYYYO...
...HYYYOOYYYO...
..HYYO....HYYO..
..HYO......HYO..
..YO........YO..
................
''')

icon('recents', {'W': 'f0f4fa', 'R': '5a8ce0', 'K': '2a3448', 'H': 'a8c4f0'}, '''
................
.....RRRRRR.....
...RRWWWWWWRR...
..RWWWWKWWWWWR..
..RWWWWKWWWWWR..
.RWWWWWKWWWWWWR.
.RWWWWWKWWWWWWR.
.RKWWWWKWWWWWKR.
.RWWWWWWKWWWWWR.
.RWWWWWWWKWWWWR.
.RWWWWWWWWKWWWR.
..RWWWWWWWWWWR..
..RWWWWKWWWWWR..
...RRWWWWWWRR...
.....RRRRRR.....
................
''')

# --------------------------------------------------------- Settings items ---
icon('theme', {'P': 'd8b078', 'H': 'f0d4a0', 'S': 'a8844c', 'R': 'e03838', 'Y': 'f0d020',
               'B': '3878e0', 'G': '30b050', 'W': 'f4f4f4'}, '''
................
.....HHHHHH.....
...HHPPPPPPPP...
..HPRRPPPPYYPP..
.HPPRRPPPPYYPPS.
.HPPPPPPPPPPPPS.
.PPBBPPPPPPPPPS.
PPPBBPPPP..PPPPS
PPPPPPPP....PPPS
PPPPPPPP....PPS.
.PPGGPPPP..PPS..
.PPGGPPPPPWWPS..
..PPPPPPPPWWS...
...SPPPPPPSS....
.....SSSSS......
................
''')

icon('volume', {'K': '4c5668', 'G': 'd8dee8', 'H': 'f4f6fa', 'W': '38bdf8'}, '''
................
........K.......
.......KK...W...
......KHK....W..
..KKKKHGK..W..W.
..KHHHGGK...W.W.
..KGGGGGK.W.W.W.
..KGGGGGK.W.W.W.
..KGGGGGK...W.W.
..KKKKGGK..W..W.
......KGK....W..
.......KK...W...
........K.......
................
................
................
''')

icon('n64quality', {'K': '2a2e38', 'D': '0c1428', 'R': 'e03838', 'Y': 'f0c818', 'G': '20a050',
                    'B': '3070e0', 'S': '6c7484'}, '''
................
.KKKKKKKKKKKKKK.
.KDDDDDDDDDDDDK.
.KDRRDDDDDDGGDK.
.KDRRDDDDDDGGDK.
.KDDDDYYYYDDDDK.
.KDDDDYYYYDDDDK.
.KDGGDDDDDDBBDK.
.KDGGDDDDDDBBDK.
.KDDDDDDDDDDDDK.
.KKKKKKKKKKKKKK.
.......SS.......
.....SSSSSS.....
................
................
................
''')

icon('clearrecent', {'K': '4c5668', 'G': 'c8d0dc', 'H': 'eef2f8', 'D': '8c96a8'}, '''
................
......KKKK......
..KKKKKKKKKKKK..
..KHHHHHHHHHHK..
..KKKKKKKKKKKK..
...KGGGGGGGGK...
...KGDGDGDGGK...
...KGDGDGDGGK...
...KGDGDGDGGK...
...KGDGDGDGGK...
...KGDGDGDGGK...
...KGGGGGGGGK...
....KKKKKKKK....
................
................
................
''')


def ring_icon(name, colour, gap, extra):
    """A 2-pixel ring (radius 5..7) with a gap between the angles in `gap`
    (degrees, 0 = right, 90 = up), plus extra pixels drawn on top."""
    import math
    grid = [['.'] * 16 for _ in range(16)]
    for y in range(16):
        for x in range(16):
            dx, dy = x - 7.5, 7.5 - y
            r = math.hypot(dx, dy)
            a = math.degrees(math.atan2(dy, dx)) % 360
            if 4.8 <= r <= 7.2 and not (gap[0] <= a <= gap[1]):
                grid[y][x] = 'C'
    for (y, x) in extra:
        grid[y][x] = 'C'
    icon(name, {'C': colour}, '\n'.join(''.join(r) for r in grid))


# Power: the IEC power symbol -- a ring open at the top, and a bar through it.
ring_icon('poweroff', 'ef4444', (55, 125), [(y, x) for y in range(0, 9) for x in (7, 8)])
# Restart: a ring open at the top right, with an arrowhead at the gap.
ring_icon('restart', '38bdf8', (20, 75), [(0, 9), (1, 9), (1, 10), (2, 9), (2, 10), (2, 11),
                                         (3, 9), (3, 10), (3, 11), (3, 12), (4, 9), (4, 10)])

# ------------------------------------------------------------- header ship --
# An original invader-style alien, not the arcade one: round eyes, curled
# feelers, a different body and feet.
icon('ship', {'G': '58e070', 'H': 'b8ffc4', 'K': '0c1810', 'g': '2c9c48'}, '''
................
................
...H........H...
....G......G....
....GG....GG....
...GGGGGGGGGG...
..GGGHGGGGHGGG..
.GGGHKGGGGHKGGG.
.GGGGGGGGGGGGGG.
.GgGGGGGGGGGGgG.
.G.GGgGGGGgGG.G.
.G.G........G.G.
...gG......Gg...
....gg....gg....
................
................
''')


def scale2x(rows):
    """Scale2x (EPX): doubles a pixel-art grid, rounding the staircase edges of
    diagonals and curves. It only ever copies a neighbour's colour, so the
    palette is unchanged. '.' (transparent) takes part like a colour, which
    smooths the outline too."""
    h, w = len(rows), len(rows[0])
    px = lambda y, x: rows[y][x] if 0 <= y < h and 0 <= x < w else '.'
    out = [[''] * (2 * w) for _ in range(2 * h)]
    for y in range(h):
        for x in range(w):
            P = px(y, x)
            A, B, C, D = px(y - 1, x), px(y, x + 1), px(y, x - 1), px(y + 1, x)
            out[2 * y][2 * x] = A if (C == A and C != D and A != B) else P
            out[2 * y][2 * x + 1] = B if (A == B and A != C and B != D) else P
            out[2 * y + 1][2 * x] = C if (D == C and D != B and C != A) else P
            out[2 * y + 1][2 * x + 1] = D if (B == D and B != A and D != C) else P
    return [''.join(r) for r in out]


UPSCALE = 2     # Scale2x passes: 16x16 art -> 64x64 icons

# Kept at their 16x16 pixels (the launcher scales them up by whole pixels):
# the header ship, whose blocky look the user preferred.
NO_UPSCALE = {'ship'}


def hires(rows, name=None):
    if name in NO_UPSCALE:
        return rows
    for _ in range(UPSCALE):
        rows = scale2x(rows)
    return rows


def write_header(path):
    out = ['/* Generated by scripts/gen-icons.py -- do not edit. Original pixel art,',
           ' * drawn at 16x16 for this project (no logos or third-party artwork),',
           ' * upscaled with Scale2x to ICON_SIZE (the header ship stays 16x16). */',
           '#pragma once',
           '#include <stdint.h>',
           '',
           'typedef struct {',
           '    const char *name;       /* g_systems[].dir_name, or favorites/recents/ship */',
           '    int size;               /* pixels per side: ICON_SIZE, or 16 */',
           '    uint32_t palette[9];    /* 0xRRGGBB, indexed by the digits in pixels */',
           '    const char *pixels;     /* size rows of size: \'.\' transparent, \'0\'..\'8\' palette */',
           '} PixelIcon;',
           '',
           f'#define ICON_SIZE {16 << UPSCALE}',
           '',
           'static const PixelIcon g_icons[] = {']
    for name, (palette, rows) in ICONS.items():
        keys = list(palette)
        assert len(keys) <= 9, f'{name}: more than 9 colours'
        pal = ', '.join(f'0x{palette[k]}' for k in keys)
        px = hires(rows, name)
        out.append(f'    {{ "{name}", {len(px)}, {{ {pal} }},')
        for r in px:
            out.append('      "' + ''.join('.' if c == '.' else str(keys.index(c)) for c in r) + '"')
        out[-1] += ' },'
    out += ['};', '']
    open(path, 'w', newline='\n').write('\n'.join(out))


def write_preview(path, scale=1):
    """The icons as the launcher draws them: 64x64, one image pixel each."""
    from PIL import Image, ImageDraw
    names = list(ICONS)
    cols = 8
    cell = (16 << UPSCALE) * scale + 24
    img = Image.new('RGB', (cols * cell, ((len(names) + cols - 1) // cols) * (cell + 18)), (16, 24, 40))
    d = ImageDraw.Draw(img)
    for i, name in enumerate(names):
        palette, rows = ICONS[name]
        rows = hires(rows, name)
        ox, oy = (i % cols) * cell + 12, (i // cols) * (cell + 18) + 8
        for y, r in enumerate(rows):
            for x, c in enumerate(r):
                if c != '.':
                    col = tuple(int(palette[c][j:j + 2], 16) for j in (0, 2, 4))
                    d.rectangle([ox + x * scale, oy + y * scale, ox + (x + 1) * scale - 1, oy + (y + 1) * scale - 1], fill=col)
        d.text((ox, oy + len(rows) * scale + 2), name, fill=(220, 226, 236))
    img.save(path)


if __name__ == '__main__':
    write_header(sys.argv[1])
    if len(sys.argv) > 2:
        write_preview(sys.argv[2])
    print(f'{len(ICONS)} icons')
